version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.10.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /Users/lijian/Documents/project/docker/file/kafka/:/var/run/docker.sock

  es:
    image: registry.cn-hangzhou.aliyuncs.com/wiselyman/es553:5.5.3
    restart: on-failure
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - /Users/lijian/Documents/project/docker/file/es/:/usr/share/elasticsearch/data:Z

  redis:
    image: sameersbn/redis
    ports:
      - '6379:6379'
    volumes:
    - /Users/lijian/Documents/project/docker/file/redis/:/var/lib/redis:Z

  postgres1:
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /Users/lijian/Documents/project/docker/file/postgres/auth:/var/lib/postgresql:Z
    environment:
    - DEBUG=false
    - DB_USER=hfcb
    - DB_PASS=hfcb
    - DB_NAME=auth
    ports:
    - "5432:5432"

  mongodb:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_USERNAME=hfcb
      - MONGODB_PASSWORD=hfcb
      - MONGODB_DATABASE=coupon
    ports:
      - "27017:27017"
    volumes:
      - /Users/lijian/Documents/project/docker/file/mongodb/:/bitnami:Z
