version: '2'

services:
  feitian-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  feitian-kafka:
    image: wurstmeister/kafka:0.10.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: feitian-kafka
      KAFKA_ZOOKEEPER_CONNECT: feitian-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  es-order:
    image: registry.cn-hangzhou.aliyuncs.com/wiselyman/es553:5.5.3
    restart: on-failure
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - /srv/docker/es-order/:/usr/share/elasticsearch/data:Z

  feitian-redis:
    image: sameersbn/redis
    volumes:
    - /srv/docker/redis:/var/lib/redis:Z

  postgres1:
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /Users/lijian/Documents/project/docker/file/postgres/auth:/var/lib/postgresql:Z
    environment:
    - DEBUG=false
    - DB_USER=hfcb
    - DB_PASS=hfcb
    - DB_NAME=auth
    ports:
    - "5432:5432"

  postgres2:
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /srv/docker/postgresql/order:/var/lib/postgresql:Z
    environment:
    - DEBUG=false
    - DB_USER=hfcb
    - DB_PASS=hfcb
    - DB_NAME=order
    ports:
    - "5433:5432"

  postgres3:
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /srv/docker/postgresql/customer:/var/lib/postgresql:Z
    environment:
    - DEBUG=false
    - DB_USER=hfcb
    - DB_PASS=hfcb
    - DB_NAME=customer
    ports:
    - "5434:5432"

  mongodb-coupon:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_USERNAME=hfcb
      - MONGODB_PASSWORD=hfcb
      - MONGODB_DATABASE=coupon
    ports:
      - "27017:27017"
    volumes:
      - /srv/docker/mongodb/coupon:/bitnami:Z

  mongodb-customer:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_USERNAME=hfcb
      - MONGODB_PASSWORD=hfcb
      - MONGODB_DATABASE=customer
    ports:
      - "27018:27017"
    volumes:
      - /srv/docker/mongodb/customer:/bitnami:Z

  mongodb-order:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_USERNAME=hfcb
      - MONGODB_PASSWORD=hfcb
      - MONGODB_DATABASE=order
    ports:
      - "27019:27017"
    volumes:
      - /srv/docker/mongodb/order:/bitnami:Z

  mongodb-employee:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_USERNAME=hfcb
      - MONGODB_PASSWORD=hfcb
      - MONGODB_DATABASE=employee
    ports:
      - "27020:27017"
    volumes:
      - /srv/docker/mongodb/employee:/bitnami:Z